import hashlib
import random
import time

transaction = ''
counter = random.randint(0, 10000000000)
Miner = hashlib.sha512(str(counter).encode("ascii")).hexdigest()
print("Miners wallet address: ", Miner, "(PCOEtest Wallet)")
print("Mining Network: PCOEtestnet on localhost:8080 - Visiting the site may cause disruption while mining (This is a test network, these are fake transactions generated by the network and the rewards for the transactions are fictional)")
print('')

while True:
    counter = counter + 1
    user1 = hashlib.sha512(str(counter).encode("ascii")).hexdigest()
    counter = counter + 1
    user2 = hashlib.sha512(str(counter).encode("ascii")).hexdigest()
    counter = counter + 1
    block = user1 + user2 + transaction
    transaction = hashlib.sha512(block.encode("ascii")).hexdigest()
    counter = counter + 1
    amount = random.randint(1, 5)

    print(user1, "gave", user2, amount, "PCOE (Phoenix Coin)")
    print('')
    print("Recording transaction...")
    time.sleep(random.randint(1, 5))
    print('')
    print("Transaction was recordered. Transaction ID: ", transaction, "1 PCOE has been rewarded to the miner")
    print('')
    print(user2, "recieved", amount, "PCOE (Phoenix Coin) from", user1)
    print('')
    print("Recording transaction...")
    time.sleep(random.randint(1, 5))
    block = user2 + user1 + transaction
    transaction = hashlib.sha512(block.encode("ascii")).hexdigest()
    print('')
    print("Transaction was recordered. Transaction ID:", transaction, "1 PCOE has been rewarded to the miner")
    print('')
